apiVersion: v1
kind: Secret
metadata:
  name: tdp-helm-oci-tdp
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  url: registry.tecnisys.com.br/tdp/charts
  name: tdp-registry
  username: username@tecnisys.com.br
  password: harbor_token
  enableOCI: "true"
