apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tdp-hive-metastore
  namespace: ${TDP_PROJECT_NAMESPACE}
  labels:
    tecnisys.io/cluster: tdp
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ${TDP_NAMESPACE}

  sources:
  - repoURL: ${HELM_CHART_REPO_URL}
    targetRevision: ${HELM_CHART_VERSION}
    chart: tdp-hive-metastore
    helm:
      valueFiles:
      - $values/current/tdp-hive-metastore/values.yaml
  
  - repoURL: '${GIT_REPO_URL}'
    targetRevision: main
    ref: values

  destination:
    server: ${KUBERNETES_SERVER}
    namespace: ${TDP_NAMESPACE}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
