apiVersion: v1
kind: Secret
metadata:
  name: tdp-devops-repo
  namespace: ${ARGOCD_NAMESPACE}
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: ${GIT_REPO_URL}
  username: ${GIT_REPO_USER}
  password: ${GIT_REPO_TOKEN_OR_PASS}
