apiVersion: v1
kind: Secret
metadata:
  name: tdp-helm-oci-tdp
  namespace: ${ARGOCD_NAMESPACE}
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  url: ${HELM_CHART_REPO_URL}
  name: tdp-registry
  username: ${TECNISYS_HELM_REGISTRY_USER}
  password: ${TECNISYS_HELM_REGISTRY_TOKEN}
  enableOCI: "true"
