apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tdp-deltalake
  namespace: tdp-project
  labels:
    tecnisys.io/cluster: tdp
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: tdp-ingestion

  sources:
  - repoURL: registry.tecnisys.com.br/tdp/charts
    targetRevision: 3.0.2
    chart: tdp-deltalake
    helm:
      valueFiles:
      - $values/current/tdp-deltalake/values.yaml
  
  - repoURL: 'https://github.com/tdp-project/tdp-ingestion.git'
    targetRevision: main
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: tdp-ingestion

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
